// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // carga .env
import { config } from "dotenv"; config({ path: "../../.env.local", override: true }); // sobreescribe con .env.local de la raíz
import { defineConfig } from "prisma/config";

// In Prisma 7, directUrl was removed. The migrate CLI uses datasource.url.
// For Supabase, port 6543 is PgBouncer transaction mode (breaks migrate due to prepared statements).
// Port 5432 on the same pooler host is session mode (supports prepared statements → works for migrate).
// The runtime PrismaClient uses DATABASE_URL via PrismaPg adapter (packages/database/src/index.ts),
// so changing this url only affects the migrate CLI, not the application.
const dbUrl = process.env["DATABASE_URL"] ?? "";
const migrateUrl = dbUrl
  .replace(":6543/", ":5432/")
  .replace("?pgbouncer=true&connection_limit=1", "")
  .replace("?pgbouncer=true", "")
  .replace("&pgbouncer=true", "");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateUrl || dbUrl,
  },
});
