// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // carga .env
import { config } from "dotenv"; config({ path: ".env.local", override: true }); // sobreescribe con .env.local
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DATABASE_URL  → pooler (Supabase port 6543) — used at runtime by Vercel serverless
    // DIRECT_URL    → direct connection (port 5432) — used only by prisma migrate CLI
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
