CREATE TABLE "Client" (
  "id"                  TEXT NOT NULL,
  "nombre"              TEXT NOT NULL,
  "correo"              TEXT NOT NULL,
  "hasDuplicateEmail"   BOOLEAN NOT NULL DEFAULT false,
  "telefono"            TEXT NOT NULL,
  "fechaReunion"        TIMESTAMPTZ NOT NULL,
  "vendedor"            TEXT NOT NULL,
  "closed"              BOOLEAN NOT NULL,
  "transcripcion"       TEXT NOT NULL,
  "industria"           TEXT,
  "tamanioEmpresa"      TEXT,
  "volumenMensajes"     TEXT,
  "canalDescubrimiento" TEXT,
  "painPoint"           TEXT,
  "integraciones"       TEXT,
  "objeciones"          TEXT,
  "urgencia"            TEXT,
  "etapaDecision"       TEXT,
  "resumenLLM"          TEXT,
  "analyzedAt"          TIMESTAMPTZ,
  "createdAt"           TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt"           TIMESTAMPTZ NOT NULL,
  CONSTRAINT "Client_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Client_nombre_correo_key" UNIQUE ("nombre", "correo")
);
